version: '3'
services:
  backend:
    image: cgrosjeanfr/courroux_backend:latest
    ports:
      - "8000:5000"
    depends_on:
      - db
  frontend:
    image: cgrosjeanfr/courroux_frontend:latest
    ports:
      - "8080:4200"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courroux
      MYSQL_USER: courroux
      MYSQL_PASSWORD: root
    ports:
      - "8083:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8808:80"

